package:
  version: "{{ PROJECT_VERSION }}"
  name: 'wfns'

source:
  path: ../../

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - numpy
    - scipy
    - gmpy2
    - setuptools
    - pytest
  run:
    - python
    - numpy
    - scipy
    - gmpy2
    - pytest

about:
  home: https://github.com/quantumelephant/olsens
  license: GNU Version 3
